[package]
rust-version.workspace = true
name = "sdkwork-content-news-service"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_content_news_service"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
